{
    "name": "JST-US-4-6",
    "planets": [
        {
            "name": "<voomoov>",
            "mass": 20000,
            "position_x": -30799.994140625,
            "position_y": -36400.015625,
            "velocity_x": -27.659225463867188,
            "velocity_y": 18.769515991210938,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 286737728,
                "radius": 800,
                "heightRange": 80,
                "waterHeight": 34,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Zeroumus[GL]",
            "mass": 50000,
            "position_x": -23800,
            "position_y": -27800.0078125,
            "velocity_x": 88.7925033569336,
            "velocity_y": -76.01655578613281,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1288345984,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Mokruush",
            "mass": 24588,
            "position_x": -99700.03125,
            "position_y": 49800.046875,
            "velocity_x": 29.930906295776367,
            "velocity_y": 59.921878814697266,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 263376240,
                "radius": 500,
                "heightRange": 53.999996185302734,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 35,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Artifactoria",
            "mass": 5000,
            "position_x": -103900.015625,
            "position_y": 47800.0390625,
            "velocity_x": 99.82440185546875,
            "velocity_y": -86.85333251953125,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 48202288,
                "radius": 1000,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 25,
                "metalClusters": 25,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Pasmero'oka",
            "mass": 10000,
            "position_x": -35299.984375,
            "position_y": -41500.01953125,
            "velocity_x": 63.26228332519531,
            "velocity_y": -61.455101013183594,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1764891776,
                "radius": 800,
                "heightRange": 35,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Otter-3",
            "mass": 10000,
            "position_x": -28100,
            "position_y": -33500,
            "velocity_x": -143.9310302734375,
            "velocity_y": 127.02174377441406,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1307361792,
                "radius": 800,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}